version: '3'
services:
  frotend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app