FROM python:3.11-alpine

COPY ./backend/requirements.txt .

WORKDIR /app

RUN pip install --no-cache-dir -r ./backend/requirements.txt

EXPOSE 8000

COPY . .

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]