FROM python:3.11-alpine

WORKDIR /app

COPY ./backend/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE $PORT

COPY ./backend/ ./

CMD python src/manage.py runserver 0.0.0.0 $PORT