FROM python:3.11-alpine

WORKDIR /app

COPY ./backend/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

COPY ./backend/ ./

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]