FROM python:3.12-alpine

WORKDIR /app

RUN pip install poetry

COPY ./backend/pyproject.toml ./backend/poetry.lock ./

RUN poetry install

EXPOSE 8000

COPY ./backend ./

RUN ls -R /app

CMD ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]