FROM python:3.11-alpine

# RUN apk add --no-cache gcc libc-dev musl-dev

WORKDIR /app

RUN pip install "poetry"

COPY ./pyproject.toml ./
COPY ./poetry.lock ./

RUN poetry install

EXPOSE $PORT

COPY ./ ./

CMD [ "python", "src/manage.py", "runserver", "--host", "0.0.0.0"]